apiVersion: v2
description: Helm Chart to deploy Google's Boutique App
keywords:
- boutique
name: boutique
version: 0.0.1
home: https://github.com/validatedpatterns/boutique-chart
maintainers:
  - name: Validated Patterns Team
    email: validatedpatterns@googlegroups.com
icon: https://validatedpatterns.io/images/validated-patterns.png
