global:
  imageRegistry: us-central1-docker.pkg.dev/google-samples/microservices-demo
  imageTag: v0.10.4
  storageClass: ""

redis:
  image: redis:alpine
  storage: 1Gi

loadgenerator:
  enabled: true
