{{- if not .Values.redis.external.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-cart-data
  labels:
    app: redis-cart
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
  type: ClusterIP
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis-cart
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          args: ["--save", ""]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 6379
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 6379
            periodSeconds: 5
          resources:
            requests:
              cpu: 70m
              memory: 200Mi
            limits:
              cpu: 125m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-cart-data
{{- end }}
